name: On PR
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: cat dist/index.js
      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Build the library
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
